title: UTAR ROBOCON Team (Sg Long Campus)
description: This is the homepage for UTAR ROBOCON Team from Sg Long Campus
theme: just-the-docs

url: https://utarroboconteam.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
